name: malware-image-experiments
channels:
  - defaults
dependencies:
  - absl-py==0.7.1
  - astor==0.8.0
  - attrs==19.3.0
  - certifi==2019.6.16
  - cffi==1.13.2
  - chardet==3.0.4
  - comet-git-pure==0.19.11
  - comet-ml==3.0.0
  - configobj==5.0.6
  - cryptography==2.8
  - everett==1.0.2
  - gast==0.2.2
  - google-pasta==0.1.7
  - grpcio==1.16.1
  - h5py==2.9.0
  - idna==2.8
  - importlib-metadata==1.2.0
  - jsonschema==3.2.0
  - keras-applications==1.0.8
  - keras-preprocessing==1.1.0
  - keras==2.2.4
  - markdown==3.1.1
  - mkl-fft==1.0.14
  - mkl-random==1.0.2
  - mkl-service==2.3.0
  - more-itertools==8.0.2
  - netifaces==0.10.9
  - numpy==1.16.4
  - nvidia-ml-py3==7.352.0
  - olefile==0.46
  - pandas==0.25.1
  - pillow==6.1.0
  - pip==19.2.2
  - protobuf==3.8.0
  - psutil==5.6.7
  - pycparser==2.19
  - pyopenssl==19.1.0
  - pyrsistent==0.15.6
  - pysocks==1.7.1
  - python-dateutil==2.8.0
  - pytz==2019.3
  - pyyaml==5.1.2
  - requests==2.22.0
  - rmate==1.0.3
  - scipy==1.3.1
  - setuptools==41.0.1
  - six==1.12.0
  - tensorboard==1.14.0
  - tensorflow-estimator==1.14.0
  - tensorflow==1.14.0
  - termcolor==1.1.0
  - urllib3==1.25.7
  - websocket-client==0.56.0
  - werkzeug==0.15.5
  - wheel==0.33.4
  - wrapt==1.11.2
  - wurlitzer==1.0.3
  - zipp==0.6.0
