name: malware-image-experiments
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.7.1
  - astor=0.8.0
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - freetype=2.9.1
  - gast=0.2.2
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - intel-openmp=2019.4
  - jpeg=9b
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - libtiff=4.0.10
  - markdown=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1d
  - pillow=6.1.0
  - pip=19.2.2
  - protobuf=3.8.0
  - python=3.7.4
  - pyyaml=5.1.2
  - readline=7.0
  - scipy=1.3.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - tk=8.6.8
  - werkzeug=0.15.5
  - wheel=0.33.4
  - wrapt=1.11.2
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
